
* Commentary: 

Bitcoin donations gratefully accepted: 13NyoPq3iusGsCtHNRT9xfA9jsqPjYtyyE

Extensions to emacs buffer-selection library (bs.el)
This extension allows you to bind keys to buffer selection configurations (using `bs-ext-config-keys'),
and optionally displays the configuration names and associated keybindings in the header line of the
*buffer-selection* buffer.
It also creates a new config called "regexp". When the "/" key is pressed the user is prompted for a regular
expression and any buffers with matching names are added to the "regexp" config.

The following new keybindings are defined:

- /        : prompt user for regular expression, place matching buffers in "regexp" config, and change to that config
- <left>   : select previous config using `bs-ext-select-previous-configuration'
- <right>  : select next config using `bs-ext-select-next-configuration'
- x        : kill buffer on current line using `bs-delete'
- R        : rename marked buffers (using regexp's like `replace-match')
- W        : write marked buffers to files (using regexp's like `replace-match')
- U        : unmark all 
- :        : apply function to marked buffers

Also if you have color-moccur installed you can use M-O to find regexp matches in marked buffers.

* Installation

 - If you have [[http://www.marmalade-repo.org/][marmalade-repo.org]], this bs-ext is part of the emacs packages you can install.  
   Just type M-x package-install bs-ext marmalade 
 - Otherwise download the library from here Lisp:bs-ext, and put it in a directory in the emacs load path, like ~/.emacs.d
 - Add (require 'bs-ext) in your ~/.emacs file
